# Generated by Django 5.0.2 on 2024-04-16 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('space', models.TextField(max_length=150)),
                ('address', models.TextField(max_length=250)),
                ('price', models.FloatField(default=0.0)),
                ('description', models.TextField(max_length=1000)),
            ],
        ),
    ]
