# Generated by Django 5.0.2 on 2024-04-16 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='property_img',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='property',
            name='address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='property',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='property',
            name='space',
            field=models.TextField(),
        ),
    ]
