# Generated by Django 5.0.2 on 2024-04-16 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_property_property_img_alter_property_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='property_img',
        ),
    ]
