# Generated by Django 5.0.2 on 2024-04-17 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_remove_property_property_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='property_img',
            field=models.ImageField(null=True, upload_to='property/'),
        ),
    ]
