# Generated by Django 5.0.4 on 2024-04-20 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_property_property_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='category',
            field=models.CharField(choices=[('FAM', 'Family'), ('BA', 'Bachelor'), ('SUB', 'Sublet')], max_length=100),
        ),
    ]
