# Generated by Django 5.0.2 on 2024-04-20 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_alter_property_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='category',
            field=models.CharField(choices=[('Family', 'Family'), ('Bachelor', 'Bachelor'), ('Sublet', 'Sublet')], max_length=100),
        ),
    ]
