# Generated by Django 5.0.2 on 2024-04-21 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_remove_property_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='name',
            field=models.TextField(default='Niribili Apartment'),
        ),
    ]
