# Generated by Django 5.0.2 on 2024-04-21 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_property_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='country',
            new_name='Area',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='division',
            new_name='Upazila',
        ),
    ]
