# Generated by Django 5.0.2 on 2024-04-21 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0007_rename_country_location_area_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='name',
        ),
    ]
