# Generated by Django 5.0.2 on 2024-04-21 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0008_remove_property_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='Area',
            new_name='area',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='Upazila',
            new_name='upazila',
        ),
    ]
