# Generated by Django 5.0.3 on 2024-04-25 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0002_alter_transaction_owner'),
        ('properties', '0009_rename_area_location_area_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PropertyOwner',
        ),
    ]
