# Generated by Django 5.0.3 on 2024-04-25 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0010_delete_propertyowner'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='title',
            field=models.TextField(null=True),
        ),
    ]
