# Generated by Django 5.0.3 on 2024-04-25 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0013_alter_property_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='title',
            field=models.TextField(null=True),
        ),
    ]
