# Generated by Django 5.0.3 on 2024-04-26 11:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Mr. Jhon', max_length=200, null=True)),
                ('user_rule', models.CharField(default='Tenant or Landlord or Admin', max_length=100, null=True)),
                ('profession', models.CharField(max_length=100, null=True)),
                ('profile_img', models.ImageField(blank=True, null=True, upload_to='profile')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
