# Generated by Django 5.0.2 on 2024-04-18 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('user_rule', models.CharField(default='Tenant or Landlord or Admin', max_length=100)),
                ('profession', models.CharField(max_length=100)),
                ('profile_img', models.ImageField(blank=True, null=True, upload_to='profile')),
            ],
        ),
    ]
