# Generated by Django 5.0.2 on 2024-04-18 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0005_profile_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='username',
        ),
    ]
