# Generated by Django 5.0.3 on 2024-04-25 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='credit',
            field=models.IntegerField(default=0),
        ),
    ]
